name: app_pikbil_mobil
description: "A new Flutter project from pikbil."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.4
  intl: ^0.19.0
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/cars/
  fonts:
    - family: Gotham-Black
      fonts:
        - asset: fonts/Gotham-Black.otf

    - family: Gotham-Bold-Italic
      fonts:
        - asset: fonts/Gotham-Bold-Italic.ttf

    - family: Gotham-Bold
      fonts:
        - asset: fonts/Gotham-Bold.otf

    - family: Gotham-Book
      fonts:
        - asset: fonts/Gotham-Book.otf

    - family: Gotham-Extra-Light-Italic
      fonts:
        - asset: fonts/Gotham-Extra-Light-Italic.otf

    - family: Gotham-Extra-Light
      fonts:
        - asset: fonts/Gotham-Extra-Light.otf

    - family: Gotham-Italic
      fonts:
        - asset: fonts/Gotham-Italic.otf

    - family: Gotham-ItalicBold
      fonts:
        - asset: fonts/Gotham-ItalicBold.otf

    - family: Gotham-Light
      fonts:
        - asset: fonts/Gotham-Light.otf

    - family: Gotham-Medium
      fonts:
        - asset: fonts/Gotham-Medium.otf

    - family: Gotham-Regular
      fonts:
        - asset: fonts/Gotham-Regular.otf

    - family: Gotham-Thin-Italic
      fonts:
        - asset: fonts/Gotham-Thin-Italic.otf

    - family: Gotham-Thin
      fonts:
        - asset: fonts/Gotham-Thin.otf
        
    - family: Gotham-Ultra
      fonts:
        - asset: fonts/Gotham-Ultra.otf
    
